#!/usr/bin/env python3
"""
SF64 Stage 2: emit adpcm_pool.bin (runtime-loaded) + generated-C descriptor table.

Key = global audio_table offset = sample_bank.rom_addr + sample.addr (the runtime
derives it as patched sampleAddr - audiotable base), same as OoT.

Oversize policy (per user): NO decimation at all.
  n <= 65534 : normal hardware voice
  n  > 65534 : stream=1, full quality, SH4 PCM-ring streamer
"""

import argparse
import os
from multiprocessing import Pool
from pathlib import Path

from sf64_audiobank_parse import parse_all
from transcode import (transcode_sample, beam_encode_cached, _HAVE_SCIPY,
                       FORCE_PCM_KEYS, FMT_PCM16, FMT_PCM8, FMT_ADPCM)
import vadpcm

ALIGN = 32
AICA_MAX = 65534
STREAM_MIN = 65535    # stream every sample over the AICA channel cap (no decimation)


def align_up(n, a):
    return (n + a - 1) & ~(a - 1)


def transcode_streamed(s):
    """Long sample: full-quality Yamaha ADPCM (beam), no decimation (SH4-streamed).
    Always ADPCM -- the SH4 ring decodes it to PCM16 at runtime, so no octave/SNR
    promotion applies (and PCM allows the full pitch range anyway)."""
    pcm = vadpcm.decode(s.data, s.codec, s.order, s.npredictors, s.book)
    adpcm, n = beam_encode_cached(pcm)
    loop_start, loop_end = (s.loop_start, s.loop_end) if s.has_loop else (0, n)
    return {"data": adpcm, "fmt": FMT_ADPCM, "nsamples": n, "loop": bool(s.has_loop),
            "loop_start": loop_start, "loop_end": min(loop_end, n),
            "downsample_shift": 0, "stream": 1}


def _transcode_one(item):
    """Pool worker: (Sample, key, is_stream) -> descriptor (pool_offset later).
    key = src_offset (bank base + addr) = runtime lookup key, used for force-PCM."""
    s, key, is_stream = item
    if is_stream:
        d = transcode_streamed(s)
    else:
        d = transcode_sample(s, force=(key in FORCE_PCM_KEYS))
        d["stream"] = 0
    d["key"] = key
    return d


def main(audiobank, audiotable, tables_json, outdir, incdir, pool_path):
    outdir = Path(outdir); incdir = Path(incdir); pool_path = Path(pool_path)
    tables, samples = parse_all(audiobank, audiotable, tables_json, with_data=True)
    bank_base = {b["index"]: b["rom_addr"] for b in tables["sample_banks"] if not b["is_ptr"]}

    # Beam encode is CPU-heavy + independent -> fan out across cores. Pool.map keeps
    # order; pool_offset assigned serially after, then re-sorted by key. Deterministic.
    items = [(s, bank_base[bank] + addr, s.nsamples >= STREAM_MIN)
             for (bank, addr), s in samples.items()]
    with Pool(os.cpu_count()) as pool:
        descs = pool.map(_transcode_one, items)

    blob = bytearray()
    for d in descs:
        d["pool_offset"] = len(blob)
        blob += d["data"]
        blob += b"\x00" * (align_up(len(blob), ALIGN) - len(blob))
    n_stream = sum(d["stream"] for d in descs)

    descs.sort(key=lambda d: d["key"])
    keys = [d["key"] for d in descs]
    assert keys == sorted(keys) and len(keys) == len(set(keys)), "keys not sorted/unique"
    for d in descs:
        assert blob[d["pool_offset"]:d["pool_offset"] + len(d["data"])] == d["data"]
        if not d["stream"]:
            assert d["nsamples"] <= AICA_MAX, (d["key"], d["nsamples"])
        assert 0 <= d["loop_start"] <= d["loop_end"] <= d["nsamples"]

    outdir.mkdir(parents=True, exist_ok=True)
    incdir.mkdir(parents=True, exist_ok=True)
    pool_path.parent.mkdir(parents=True, exist_ok=True)
    pool_path.write_bytes(blob)

    h = ["/* Auto-generated by tools/aica/sf64_emit.py. Do not edit. */",
         "#ifndef AICA_SAMPLE_TABLE_H", "#define AICA_SAMPLE_TABLE_H", "#include <stdint.h>", "",
         "typedef struct {",
         "    uint32_t src_offset;       /* global audio_table offset (lookup key) */",
         "    uint32_t pool_offset;      /* byte offset into adpcm_pool.bin */",
         "    uint32_t byte_len;         /* Yamaha ADPCM byte length */",
         "    uint32_t nsamples;         /* PCM sample count (may exceed 65534 if streamed) */",
         "    uint32_t loop_start;",
         "    uint32_t loop_end;",
         "    uint8_t  loop_flag;",
         "    uint8_t  downsample_shift; /* 0, or 1 = 2x-decimated, play at freq>>1 */",
         "    uint8_t  stream;           /* 1 = too long for one channel; SH4-streamed */",
         "    uint8_t  fmt;              /* AICA_SM_* format: 0=PCM16 1=PCM8 2=ADPCM */",
         "} AicaSampleDesc;", "",
         f"#define AICA_SAMPLE_COUNT {len(descs)}",
         f"#define AICA_ADPCM_POOL_SIZE {len(blob)}u",
         "extern const AicaSampleDesc gAicaSampleTable[AICA_SAMPLE_COUNT];", "", "#endif"]
    (incdir / "aica_sample_table.h").write_text("\n".join(h) + "\n")

    c = ["/* Auto-generated by tools/aica/sf64_emit.py. Do not edit. */",
         '#include "aica_sample_table.h"', "",
         "const AicaSampleDesc gAicaSampleTable[AICA_SAMPLE_COUNT] = {"]
    for d in descs:
        c.append(f"    {{ 0x{d['key']:06X}, 0x{d['pool_offset']:06X}, {len(d['data']):>6}, "
                 f"{d['nsamples']:>6}, {d['loop_start']:>6}, {d['loop_end']:>6}, "
                 f"{1 if d['loop'] else 0}, {d['downsample_shift']}, {d['stream']}, {d['fmt']} }},")
    c.append("};")
    (outdir / "aica_sample_table.c").write_text("\n".join(c) + "\n")

    n16 = sum(1 for d in descs if d["fmt"] == FMT_PCM16)
    n8 = sum(1 for d in descs if d["fmt"] == FMT_PCM8)
    nad = sum(1 for d in descs if d["fmt"] == FMT_ADPCM)
    print(f"sf64_emit: {len(descs)} descs  ADPCM={nad} PCM16={n16} PCM8={n8} ({n_stream} streamed), "
          f"pool {len(blob):,} B -> {pool_path}"
          f"{'' if _HAVE_SCIPY else '  [stdlib decimate fallback]'}")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--audiobank", required=True)
    ap.add_argument("--audiotable", required=True)
    ap.add_argument("--tables", required=True)
    ap.add_argument("--outdir", required=True)
    ap.add_argument("--incdir")
    ap.add_argument("--pool", required=True)
    a = ap.parse_args()
    main(a.audiobank, a.audiotable, a.tables, a.outdir, a.incdir or a.outdir, a.pool)
