/* Auto-generated by tools/aica/sf64_emit.py. Do not edit. */
#ifndef AICA_SAMPLE_TABLE_H
#define AICA_SAMPLE_TABLE_H
#include <stdint.h>

typedef struct {
    uint32_t src_offset;       /* global audio_table offset (lookup key) */
    uint32_t pool_offset;      /* byte offset into adpcm_pool.bin */
    uint32_t byte_len;         /* Yamaha ADPCM byte length */
    uint32_t nsamples;         /* PCM sample count (may exceed 65534 if streamed) */
    uint32_t loop_start;
    uint32_t loop_end;
    uint8_t  loop_flag;
    uint8_t  downsample_shift; /* 0, or 1 = 2x-decimated, play at freq>>1 */
    uint8_t  stream;           /* 1 = too long for one channel; SH4-streamed */
    uint8_t  fmt;              /* AICA_SM_* format: 0=PCM16 1=PCM8 2=ADPCM */
} AicaSampleDesc;

#define AICA_SAMPLE_COUNT 1132
#define AICA_ADPCM_POOL_SIZE 8209888u
extern const AicaSampleDesc gAicaSampleTable[AICA_SAMPLE_COUNT];

#endif
